In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
classes = {
    0: 'False Positive',
    1: 'Confirmed Planet',
}
candidates = pd.read_csv('candidates_predictions_with_coords.csv')
candidates.head()

      kepid kepoi_name         ra        dec  predicted   probability
0  10000162  K04902.01  286.33545  46.917831        0.0  1.033783e-22
1  10000941  K04146.02  286.81937  46.911690        1.0  9.999953e-01
2  10002049  K07270.01  287.46475  46.968410        1.0  9.999773e-01
3  10003058  K04519.01  288.01013  46.978519        0.0  1.998035e-12
4  10005788  K01940.02  289.35202  46.973728        0.0  4.341749e-01

In [10]:
all_data = pd.read_csv('../csv/cumulative_2025.11.25_08.30.17.csv', skiprows=144)
all_data.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_vet_stat,koi_vet_date,koi_pdisposition,koi_score,koi_fpflag_nt,...,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,0.200,0.160,0.200,0.170,0.080,0.130,0.310,0.170,0.320,0.160
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,Done,2018-08-16,CANDIDATE,0.969,0,...,0.000,0.480,0.390,0.360,0.490,0.340,0.120,0.730,0.500,0.450
2,3,10811496,K00753.01,NaN,CANDIDATE,Done,2018-08-16,CANDIDATE,0.000,0,...,-0.034,0.070,0.042,0.072,0.002,0.071,-0.027,0.074,0.027,0.074
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,Done,2018-08-16,FALSE POSITIVE,0.000,0,...,0.147,0.078,0.289,0.079,-0.257,0.072,0.099,0.077,0.276,0.076
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,-0.090,0.180,0.100,0.140,0.070,0.180,0.020,0.160,0.070,0.200

In [11]:
# merge candidates with all_data to get the star names and magnitudes
magnitudes_cols = [col for col in all_data.columns if 'mag' in col]
magnitudes_cols

candidates = candidates.merge(all_data[['kepoi_name'] + magnitudes_cols], on='kepoi_name' , how='left', validate='one_to_one')
candidates.head()

,kepid,kepoi_name,ra,dec,predicted,probability,koi_kepmag,koi_gmag,koi_rmag,koi_imag,koi_zmag,koi_jmag,koi_hmag,koi_kmag
0,10000162,K04902.01,286.33545,46.917831,0.0,1.033783e-22,15.149,15.948,15.055,14.806,14.665,13.507,12.949,12.830
1,10000941,K04146.02,286.81937,46.911690,1.0,9.999953e-01,13.632,14.343,13.565,13.327,13.215,12.204,11.738,11.657
2,10002049,K07270.01,287.46475,46.968410,1.0,9.999773e-01,15.362,15.810,15.310,15.169,15.104,14.239,13.887,13.804
3,10003058,K04519.01,288.01013,46.978519,0.0,1.998035e-12,14.744,15.092,14.688,14.595,14.569,13.734,13.480,13.470
4,10005788,K01940.02,289.35202,46.973728,0.0,4.341749e-01,15.389,16.504,15.334,14.912,14.690,13.540,12.907,12.821

In [13]:
candidates['predicted'] = candidates['predicted'].map(classes)
candidates.head()

,kepid,kepoi_name,ra,dec,predicted,probability,koi_kepmag,koi_gmag,koi_rmag,koi_imag,koi_zmag,koi_jmag,koi_hmag,koi_kmag
0,10000162,K04902.01,286.33545,46.917831,False Positive,1.033783e-22,15.149,15.948,15.055,14.806,14.665,13.507,12.949,12.830
1,10000941,K04146.02,286.81937,46.911690,Confirmed Planet,9.999953e-01,13.632,14.343,13.565,13.327,13.215,12.204,11.738,11.657
2,10002049,K07270.01,287.46475,46.968410,Confirmed Planet,9.999773e-01,15.362,15.810,15.310,15.169,15.104,14.239,13.887,13.804
3,10003058,K04519.01,288.01013,46.978519,False Positive,1.998035e-12,14.744,15.092,14.688,14.595,14.569,13.734,13.480,13.470
4,10005788,K01940.02,289.35202,46.973728,False Positive,4.341749e-01,15.389,16.504,15.334,14.912,14.690,13.540,12.907,12.821

In [14]:
candidates.to_csv('candidates_predictions_with_coords_and_magnitudes.csv', index=False)

In [13]:
import pandas as pd
df_2022 = pd.read_csv('../csv/cumulative_2022.09.30_09.06.43.csv', skiprows=144)
df_2025 = pd.read_csv('../csv/cumulative_2025.11.25_08.30.17.csv', skiprows=144)

candidates_2022 = df_2022[df_2022['koi_disposition'] == 'CANDIDATE']
candidates_2025 = df_2025[df_2025['koi_disposition'] == 'CANDIDATE']

print(candidates_2025.shape[0], candidates_2022.shape[0])
print(candidates_2022.shape[0] - candidates_2025.shape[0])
id_2022 = candidates_2022['kepoi_name'].unique()
id_2025 = candidates_2025['kepoi_name'].unique()
print(len(id_2022), len(id_2025))
print(len(id_2022) - len(id_2025))
changed_candidates = candidates_2022[~candidates_2022['kepoi_name'].isin(id_2025)]
changed_candidates.shape

changed_candidates.to_csv('../results/changed_candidates.csv', index=False)

1979 2056
77
2056 1979
77